on:
  push:
    branches:
      - "feature/build-pipeline"
    #tags:
    #  - 'v*'

name: Create release

jobs:
  build:
    name: Create release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build mod zip
        run: |
          VERSION=$(jq -r .version src/server/package.json)
          mkdir factorio2mqtt_"$VERSION"
          cp src/addon/* factorio2mqtt_"$VERSION"
          mkdir factorio2mqtt_"$VERSION"/server
          cp src/server/.dockerignore factorio2mqtt_"$VERSION"/server
          cp src/server/.env factorio2mqtt_"$VERSION"/server
          cp src/server/docker-compose.yml factorio2mqtt_"$VERSION"/server
          cp src/server/Dockerfile factorio2mqtt_"$VERSION"/server
          cp src/server/index.js factorio2mqtt_"$VERSION"/server
          cp src/server/package*.json factorio2mqtt_"$VERSION"/server
          find factorio2mqtt_"$VERSION"
          zip -r factorio2mqtt_"$VERSION".zip factorio2mqtt_"$VERSION"
          ls -la

      #- name: Release
        #uses: softprops/action-gh-release@v2
        #if: startsWith(github.ref, 'refs/tags/')
        #with:
          #files: factorio2mqtt_"$VERSION".zip